export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_HALLS = 'GET_HALLS';
export const SET_DOCTOR_RENDER = 'SET_DOCTOR_RENDER';
export const SET_CLADMINNAV_RENDER = 'SET_CLADMINNAV_RENDER';
export const SET_CLINIC_RENDER = 'SET_CLINIC_RENDER';